import json
import os
from openai import OpenAI
from app.services.prompt_builder import build_analyst_prompt

def generate_operations(question: str, dataset_metadata: dict, schema: list[dict]) -> dict:
    """Uses LLM to convert a user question into a Polars query plan (JSON)."""
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not configured")

    client = OpenAI(api_key=api_key)
    model = os.environ.get("OPENAI_MODEL", "gpt-4.1-mini")
    
    prompt = build_analyst_prompt(question, dataset_metadata, schema)
    
    response = client.chat.completions.create(
        model=model,
        messages=[
            {
                "role": "system",
                "content": "You are a professional Python data analyst specializing in Polars. You always return responses in JSON format."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0.0,
        response_format={"type": "json_object"}
    )
    
    content = response.choices[0].message.content.strip()
    
    # Strip markdown block formatting if present (usually not present with JSON mode, but safe to handle)
    if content.startswith("```"):
        lines = content.splitlines()
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines[-1].startswith("```"):
            lines = lines[:-1]
        content = "\n".join(lines).strip()
        
    try:
        data = json.loads(content)
        # Ensure standard keys are present
        if "polars_code" not in data:
            raise ValueError("LLM response is missing 'polars_code' field")
        if "explanation" not in data:
            data["explanation"] = "Query generated by Dataframe Agent."
        if "required_columns" not in data:
            data["required_columns"] = []
        return data
    except json.JSONDecodeError as e:
        raise RuntimeError(f"Failed to parse LLM JSON response: {e}. Raw content: {content}")
