from typing import Dict, Any, List

def build_copilot_prompt(
    user_request: str,
    context: Dict[str, Any],
    history: List[Dict[str, Any]] = None
) -> str:
    """
    Constructs the prompt for the LLM to generate a pipeline from user request,
    dataset context, and conversation history.
    """
    # 1. Format history context
    history_str = ""
    if history:
        history_str = "\n## Conversation History / User Preferences:\n"
        for turn in history:
            history_str += f"- User: {turn.get('question')}\n"
            history_str += f"- Assistant: {turn.get('answer')}\n"
            if turn.get("user_feedback"):
                history_str += f"  - User correction/preference: {turn.get('user_feedback')}\n"
                
    # 2. Format dataset columns and issues
    cols_str = "\n".join([f"- {col['name']} ({col['type']}), Semantic: {col['semantic_type']}" for col in context.get("columns", [])])
    issues_str = "\n".join([f"- Column: {i['column']}, Issue: {i['issue_type']}, Count: {i['count']}, Severity: {i['severity']}" for i in context.get("detected_issues", [])])
    recs_str = "\n".join([f"- Column: {r['column']}, Recommendation: {r['recommended_action']}, Reason: {r['reason']}" for r in context.get("recommendations", [])])
    
    return f"""You are a Senior Data Pipeline Architect. Your job is to convert natural language instructions into an executable data cleaning pipeline.

## Available Transformations and Parameters:
1. `remove_duplicates`: Deduplicates rows. Parameters: {{"subset": ["col_name"]}} (optional subset list)
2. `fill_missing`: Imputes missing/null values. Parameters: {{"column": "col_name", "method": "median|mode|forward_fill|value", "fill_value": any}} (required column and method; fill_value required only if method is 'value')
3. `drop_column`: Removes a column. Parameters: {{"column": "col_name"}}
4. `rename_column`: Renames a column. Parameters: {{"column": "col_name", "new_name": "new_col_name"}}
5. `convert_type`: Casts column type. Parameters: {{"column": "col_name", "target_type": "Integer|Float|Date|Boolean|Integer-like|Float-like"}}
6. `remove_outliers`: Caps numeric outliers. Parameters: {{"column": "col_name", "method": "cap|remove"}} (optional method, default "cap")
7. `normalize`: Scales numeric values. Parameters: {{"column": "col_name", "method": "min_max|z_score"}} (optional method, default "min_max")
8. `encode_categories`: Categorical encoding. Parameters: {{"column": "col_name", "method": "label|one_hot"}} (optional method, default "label")
9. `standardize_text`: Semantic cleaning of standard formats (RAM/Price/Weight). Parameters: {{"column": "col_name"}} (optional column; if omitted, cleans all matched columns)
10. `trim_whitespace`: Strips whitespace. Parameters: {{"column": "col_name"}} (optional column)
11. `lowercase`: Convert string to lowercase. Parameters: {{"column": "col_name"}}
12. `uppercase`: Convert string to uppercase. Parameters: {{"column": "col_name"}}
13. `replace_values`: Find and replace. Parameters: {{"column": "col_name", "old_value": any, "new_value": any}}
14. `split_column`: Splits a string column. Parameters: {{"column": "col_name", "delimiter": str, "new_columns": ["col1", "col2"]}}
15. `merge_columns`: Merges string columns. Parameters: {{"columns": ["col1", "col2"], "new_column": "new_col_name", "separator": str}} (separator optional)
16. `feature_engineering`: Creates derived features. Parameters: {{"column": "col_name", "operation": "log|square|sqrt|bin", "bin_edges": [float]}} (bin_edges optional)

## Dataset Schema:
Columns available in the dataset:
{cols_str}

## Identified Quality Issues:
{issues_str}

## System Recommendations:
{recs_str}
{history_str}

## Instructions:
1. Translate the user request into a sequence of transformations.
2. ONLY use the 16 registered transformations listed above. Never invent new ones.
3. Every column reference in parameters must refer to a column that exists in the dataset schema, or is generated by a previous step (e.g. from `split_column`, `merge_columns`, or `feature_engineering`).
4. Respect all user preferences and history. If user says "Don't remove duplicates" or similar corrections, obey them.
5. Return ONLY a valid JSON object matching the output schema. No markdown block formatting, no comments, no explanations.

## Output Format:
Your output must be a single valid JSON object structured exactly as:
{{
  "pipeline_name": "Basic Cleaning or specific name",
  "description": "Short explanation of the pipeline objectives",
  "steps": [
    {{
      "transformation": "transformation_name",
      "params": {{
        "parameter_key": "parameter_value"
      }}
    }}
  ]
}}

## User Request:
"{user_request}"
"""
